---
# tasks file for cloudflared
- name: Define required variables
  set_fact:
    daemon_location: "{{ install_target_dir }}/cloudflared"
    cf_binary_filename: "{{ cf_binaries[ansible_machine].filename_tgz }}"
- name: Cleanup legacy stuff
  include_tasks: cleanup.yml
  with_dict: "{{ tunnels }}"
  when: do_legacy_cleanup
- name: Download and install cloudflared
  include_tasks: install.yml
- name: Install cloudflared
  include_tasks: configure.yml
  when: not install_only
- name: Configure tunnels
  include_tasks: configure-tunnels.yml
  when: not install_only
