- name: Stop systemd service {{ item }}
  systemd:
    name: "{{ systemd_filename }}@{{ item }}"
    state: stopped
    enabled: no
    daemon_reload: yes
    no_block: no
- name: Delete config file for tunnel '{{ item }}'
  file:
    state: absent
    path: "{{ config_dir_tunnels }}/{{ item }}.yml"
- name: Delete logfile for tunnel '{{ item }}'
  file:
    state: absent
    path: "/var/log/cloudflared_{{ item }}.log"
- name: Delete systemd service file for tunnel '{{ item }}'
  file:
    state: absent
    path: "{{ systemd_filename }}@{{ item }}"